#!/usr/bin/env python3
"""Every state's current legislators and statewide executive officers, from
Open States' public people data (github.com/openstates/people, public domain),
written to data/states/people/<st>.json for the sync Worker's `states-officials`
step. Run weekly by the "Refresh state officials" workflow; never edit the
output by hand. See docs/states.md.

    python3 tools/build_state_people.py <path to a checkout of openstates/people>

California is left out: its legislators come from the Open States API (with the
Calaveras district check) and its statewide officers are entered by hand in
data/state-executive-officials.json.

Only what the files state is kept: a current role (no end date, or an end date
still ahead), its district as written, the party listed without an end date,
and the role's own start and end dates. Nothing is filled in or guessed; a
person without a current role or an http(s) source is left out.
"""
import datetime
import json
import re
import sys
from pathlib import Path

import yaml  # installed by the workflow (pyyaml)

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "states" / "people"
SKIP = {"ca", "us"}  # California: see above. "us": Congress, loaded from Congress.gov.
LEGISLATIVE = {"upper", "lower", "legislature"}
TODAY = datetime.date.today().isoformat()


def current(roles, kinds=None):
    """Roles held today: no end date, or one still ahead."""
    out = []
    for r in roles or []:
        end = str(r.get("end_date") or "")
        if end and end < TODAY:
            continue
        start = str(r.get("start_date") or "")
        if start and start > TODAY:
            continue
        if kinds is None or r.get("type") in kinds:
            out.append(r)
    return out


def party(p):
    names = [x.get("name") for x in p.get("party") or [] if not x.get("end_date") and x.get("name")]
    return names[-1] if names else None


def http(u):
    return isinstance(u, str) and re.match(r"^https?://", u) is not None


def official_site(urls, st):
    """The first link on a government website (the state's own pages), else None."""
    for u in urls:
        if re.search(r"\.(gov|us)(/|$)|legislature|legis|senate\.|house\.|assembly\.", u, re.I) and "wikipedia" not in u:
            return u
    return None


def person(p, role, st):
    links = [x.get("url") for x in p.get("links") or [] if http(x.get("url"))]
    sources = [x.get("url") for x in p.get("sources") or [] if http(x.get("url"))]
    source = official_site(sources, st) or official_site(links, st) or (sources[0] if sources else None) or (links[0] if links else None)
    if not source:
        return None
    return {
        "id": p["id"],  # ocd-person/<uuid>
        "name": p.get("name"),
        "family_name": p.get("family_name") or None,
        "party": party(p),
        "type": role.get("type"),
        "district": str(role["district"]) if role.get("district") is not None else None,
        "start_date": str(role.get("start_date") or "") or None,
        "end_date": str(role.get("end_date") or "") or None,
        "image": p.get("image") if http(p.get("image")) else None,
        "website": links[0] if links else None,
        "source_url": source,
    }


def main(repo):
    data = Path(repo) / "data"
    OUT.mkdir(parents=True, exist_ok=True)
    summary = []
    for d in sorted(x for x in data.iterdir() if x.is_dir()):
        st = d.name
        if st in SKIP:
            continue
        legislators, executives = [], []
        for f in sorted((d / "legislature").glob("*.yml")):
            p = yaml.safe_load(f.read_text())
            for r in current(p.get("roles"), LEGISLATIVE):
                rec = person(p, r, st)
                if rec:
                    legislators.append(rec)
        for f in sorted((d / "executive").glob("*.yml")):
            p = yaml.safe_load(f.read_text())
            for r in current(p.get("roles")):
                if r.get("type") in LEGISLATIVE or "mayor" in str(r.get("type")):
                    continue
                rec = person(p, r, st)
                if rec:
                    executives.append(rec)
        if not legislators and not executives:
            continue
        doc = {
            "_readme": "Generated by tools/build_state_people.py from github.com/openstates/people (public domain); don't edit by hand.",
            "st": st.upper(),
            "source": f"https://github.com/openstates/people/tree/main/data/{st}",
            "built_on": TODAY,
            "legislators": legislators,
            "executives": executives,
        }
        (OUT / f"{st}.json").write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n")
        summary.append(f"{st.upper()} {len(legislators)}+{len(executives)}")
    print(f"{len(summary)} states and territories: " + ", ".join(summary))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
