#!/usr/bin/env node
// Turns tools/build_ca_campaign.py's output into data/ca-campaign.json:
// employers and organizations sorted into industries by the same keyword rules
// as federal funding (workers/sync/src/funding/industry.js), so the rules live
// in one place, and long lists cut to what the pages show.
//
//   node tools/ca_campaign_finish.mjs <work-dir>/ca-campaign-raw.json data/ca-campaign.json
//
// Individuals are never named: they arrive here only as totals and by employer.
// An employer is kept for the page only when at least MIN_EMPLOYER_DONORS people
// gave, as for members of Congress; every employer still counts in the
// industry totals. "Retired", "Not employed", "Self-employed" and the like
// aren't employers: they're counted in individual totals only.
import { readFileSync, writeFileSync } from "node:fs";
import { classify, NOT_EMPLOYED } from "../workers/sync/src/funding/industry.js";

export const MIN_EMPLOYER_DONORS = 3;
const TOP = 10;
const round = (n) => Math.round(n * 100) / 100;

export function finishCycle(c) {
  const industries = new Map();
  const add = (k, n) => industries.set(k, (industries.get(k) || 0) + n);
  const employers = [];
  const notEmployed = { total: 0, count: 0 };
  for (const e of c.employers || []) {
    if (!e.employer || NOT_EMPLOYED.test(e.employer)) {
      notEmployed.total += e.total;
      notEmployed.count += e.count;
      continue;
    }
    const industry = classify(e.employer);
    add(industry, e.total);
    employers.push({ employer: e.employer, industry, total: e.total, count: e.count });
  }
  const organizations = (c.organizations || []).map((o) => {
    const industry = classify(o.name);
    add(industry, o.total);
    return { name: o.name, kind: o.kind, industry, total: o.total, count: o.count, filer_id: o.filer_id || null };
  });
  const ie = c.ie || [];
  return {
    raised: c.raised,
    spent: c.spent,
    statements: c.statements,
    individuals: c.individuals,
    not_employed: { total: round(notEmployed.total), count: notEmployed.count },
    industries: [...industries].map(([industry, total]) => ({ industry, total: round(total) })).sort((a, b) => b.total - a.total),
    employers: employers.filter((e) => e.count >= MIN_EMPLOYER_DONORS).slice(0, TOP),
    organizations: organizations.slice(0, TOP),
    ie: [...ie.filter((x) => x.support_oppose === "support").slice(0, TOP), ...ie.filter((x) => x.support_oppose === "oppose").slice(0, TOP)],
  };
}

export function finishPerson(p) {
  return { name: p.name, committees: p.committees, cycles: Object.fromEntries(Object.entries(p.cycles || {}).map(([k, c]) => [k, finishCycle(c)])) };
}

export function finish(raw) {
  return {
    _readme:
      "Generated by tools/build_ca_campaign.py and tools/ca_campaign_finish.mjs from the Cal-Access export; don't edit by hand. For the statewide officers (officials) and every legislative candidate with a statement since 2025 (seats): their campaign committees and Form 460 totals, contributions itemized on Schedule A (individuals only as totals and by employer, never by name; organizations by name), and Form 496 independent expenditures for and against them, since " + raw.since + ". Industries are approximate (keyword rules).",
    source: raw.source,
    export_modified: raw.export_modified,
    generated: raw.generated,
    since: raw.since,
    officials: Object.fromEntries(Object.entries(raw.officials || {}).map(([k, p]) => [k, finishPerson(p)])),
    seats: Object.fromEntries(Object.entries(raw.seats || {}).map(([k, people]) => [k, people.map(finishPerson)])),
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const [, , input, output] = process.argv;
  if (!input || !output) {
    console.error("usage: node tools/ca_campaign_finish.mjs <raw.json> <out.json>");
    process.exit(2);
  }
  const doc = finish(JSON.parse(readFileSync(input, "utf8")));
  writeFileSync(output, JSON.stringify(doc, null, 1) + "\n");
  const seats = Object.values(doc.seats);
  console.log(`statewide: ${Object.keys(doc.officials).length}; seats: ${seats.length}; candidates: ${seats.reduce((n, s) => n + s.length, 0)}; ${(JSON.stringify(doc).length / 1e6).toFixed(1)} MB`);
}
